//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BlogEntities : DbContext
    {
        public BlogEntities()
            : base("name=BlogEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_Article> tb_Article { get; set; }
        public virtual DbSet<tb_ArticleClassification> tb_ArticleClassification { get; set; }
        public virtual DbSet<tb_ErrorLog> tb_ErrorLog { get; set; }
        public virtual DbSet<tb_OperateLog> tb_OperateLog { get; set; }
        public virtual DbSet<tb_SensitiveWord> tb_SensitiveWord { get; set; }
    }
}
