//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ErrorLog
    {
        public string Id { get; set; }
        public string ErrorName { get; set; }
        public string ErrorContent { get; set; }
        public string Page { get; set; }
        public System.DateTime DateTime { get; set; }
        public string Ip { get; set; }
        public int OperateTyep { get; set; }
    }
}
